title: Configuration
data:
  error_404_entry: home
  copyright_name: LoansBySheilla
  copyright_since: 2025
  privacy_statement_type: entry
  privacy_statement_entry: aef46f83-2cbf-4187-b932-5508c2bb90da
  cookie_notice_type: none
